-- Extensiones de base
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ✅ AJOUT : Créer tous les schémas nécessaires
CREATE SCHEMA IF NOT EXISTS organization;
CREATE SCHEMA IF NOT EXISTS auth;
CREATE SCHEMA IF NOT EXISTS iot;
CREATE SCHEMA IF NOT EXISTS alerts;
CREATE SCHEMA IF NOT EXISTS raw_data;

-- Permissions pour jorge sur tous les schémas
GRANT ALL ON SCHEMA public, organization, auth, iot, alerts, raw_data TO jorge;

-- Permissions par défaut pour les futures tables
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA organization GRANT ALL ON TABLES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON TABLES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA iot GRANT ALL ON TABLES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA alerts GRANT ALL ON TABLES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_data GRANT ALL ON TABLES TO jorge;

-- Permissions pour les séquences
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA organization GRANT ALL ON SEQUENCES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON SEQUENCES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA iot GRANT ALL ON SEQUENCES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA alerts GRANT ALL ON SEQUENCES TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_data GRANT ALL ON SEQUENCES TO jorge;

-- Permissions pour les fonctions
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA organization GRANT ALL ON FUNCTIONS TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT ALL ON FUNCTIONS TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA iot GRANT ALL ON FUNCTIONS TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA alerts GRANT ALL ON FUNCTIONS TO jorge;
ALTER DEFAULT PRIVILEGES IN SCHEMA raw_data GRANT ALL ON FUNCTIONS TO jorge;

-- Message de confirmation
DO $$
BEGIN
    RAISE NOTICE '=== INIT.SQL EJECUTADO EXITOSAMENTE ===';
    RAISE NOTICE 'Schémas créés: public, organization, auth, iot, alerts, raw_data';
    RAISE NOTICE '¡Listo para migraciones de Prisma!';
    RAISE NOTICE '====================================='; 
END $$;