GRANT CREATE ON DATABASE "${DB_NAME}" TO ${DB_USER};

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_USER}
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_USER}
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${DB_USER};

ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_USER}
GRANT EXECUTE ON FUNCTIONS TO ${DB_USER};

DO $$
BEGIN
  RAISE NOTICE '=== INIT.SQL OK ===';
END $$;