GRANT CREATE ON DATABASE "TesisIot" TO jorge;

REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO PUBLIC;

ALTER DEFAULT PRIVILEGES FOR ROLE jorge
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO jorge;

ALTER DEFAULT PRIVILEGES FOR ROLE jorge
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO jorge;

ALTER DEFAULT PRIVILEGES FOR ROLE jorge
GRANT EXECUTE ON FUNCTIONS TO jorge;

DO $$
BEGIN
  RAISE NOTICE '=== INIT.SQL OK ===';
END $$;